Add two java file
EranosyanVova/Java pull request #3
Opened 2021-11-05 13:31 UTC by EranosyanVova

I did it!

2021-11-05 13:59 UTC, lo0ken requested changes

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/Main.java
> +        boolean algCheck = false;
константы объявляются через static final 
https://stackoverflow.com/questions/66066/what-is-the-best-way-to-implement-constants-in-java

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/Main.java
> +        StringBuilder string = new StringBuilder("");
StringBuilder вроде по умолчанию создается с пустой строкой, поэтому в конструктор ничего передавать не нужно. Так же название переменной string не корректное - string  это строка, а у тебя билдер

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/Main.java
> +            if (args[i].equals("-mode"))
все if - else конструкции принято писать всегда с фигурными скобками, даже если 1 действие

удобней читается и легче вносить изменения

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/Main.java
> +        } else encDec.setAlgorithm(new Unicode(), mode);
все if - else конструкции принято писать всегда с фигурными скобками, даже если 1 действие

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/Main.java
> +                 FileWriter writer = new FileWriter(new File(out), false)) {
лишний пробел в начале строки

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/Main.java
> +                writer.write(string.toString());
вот и путанница от не правильного названия билдера - если смотришь в первый раз - не понятно зачем строку приводить к строке - ведь она уже и так строка)

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/EncDec.java
> +
для каждого файла / интерфейса - отдельный файл

названия классов лучше не сокращать для читаемости
пусть лучше будет длинным - но говорящим
предлагаю что-то типо Cryptor

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/EncDec.java
> +        else this.algorithm.decrypted(string, key);
все if - else конструкции принято писать всегда с фигурными скобками, даже если 1 действие

this тут не нужен, так как нету одинаковых имен в рамках метода

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/EncDec.java
> +        if (mode.equals("enc") || mode.equals(""))
mode.equals("") заменить на mode.isEmpty(). enc можно вынести в константу

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/EncDec.java
> +    public void useAlgorithm(StringBuilder string, int key) {
string - некорректное наименование для билдера

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/EncDec.java
> +    void decrypted(StringBuilder string, int key);
наименования методов должны быть глаголами

encrypt() decrypt()

encrypted / decrypted больше похожы не на действие а на состояние
К примеру если бы у тебя был обьект, можно было бы хранить его состояние в boolen переменной
Зашифрован он или нет - encrypted

У тебя же это действие - зашифровать / расшифровать

так же неккоректное наименование билдера

что бы переименовать метод сразу во всех местах - попробуй комбинацию клавиш Shift + F6

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/EncDec.java
> +class Shift implements EncodingAlgorithm {
Shift не очень понятно что это, ShiftAlgorithm лучше, и так же в других классах

+ опечатка, не Algoritm а Algorithm

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/EncDec.java
> +            if (string.charAt(i) >= 97 && string.charAt(i) <= 122) {
97 и 122 здесь - магические числа https://stackoverflow.com/questions/47882/what-is-a-magic-number-and-why-is-it-bad

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/EncDec.java
> +                string.setCharAt(i, (char)((string.charAt(i) - 97 - key) % 26 >= 0 ? 97 + (string.charAt(i) - 97 - key) % 26 : 123 + (string.charAt(i) - 97 - key) % 26));
магические числа

2021-11-05 13:59 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/EncDec.java
> +class Unicode implements EncodingAlgorithm {
наименование, вынести в отделньый файл

2021-11-05 23:30 UTC, EranosyanVova commented on Encryption-Decryption/src/encryptdecrypt/Main.java
> +        boolean algCheck = false;
Это не константы

2021-11-06 10:35 UTC, lo0ken requested changes

2021-11-06 10:35 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/Cryptor.java
> +    static final String encryptMode = "enc";
не забывай указывать модификатор доступа - в данном месте encryptMode нигде не используется - значит private

константы принято описывать в самом верху класса, т. е. в данном случае выше полей класса
наименовуются константы в следующем виде: ENCRYPT_MODE

2021-11-06 10:35 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/ShiftAlgorithm.java
> +    public static final int LAST_ENGLISH_LATTER_CODE = 122;
LETTER

2021-11-06 10:35 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/ShiftAlgorithm.java
> +            if (stringBuilder.charAt(i) >= FIRST_ENGLISH_LATTER_CODE && stringBuilder.charAt(i) <= LAST_ENGLISH_LATTER_CODE) {
такой код плохо читается, не очень понятно что проверяется в ифе. Является ли символ английской буквой?
Тогда это должно быть очевидно

Еще момент, что громоздкий код получился и в самом условии и в теле ифа, всё время повторяется stringBuilder.charAt(i) - это можно вынести в переменную перед ifom. И назвать к примеру: char currentLetter = stringBuilder.charAt(i) и использовать её везде

Сложные и не очевидные условия лучше выносить в отдельный метод, например можешь сделать метод isEnglishLetter() и у тебя получится хороший if(isEnglishLetter(currentLetter)) { ..... }

2021-11-06 10:35 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/ShiftAlgorithm.java
> +                stringBuilder.setCharAt(i, (char)(FIRST_ENGLISH_LATTER_CODE + (stringBuilder.charAt(i) - FIRST_ENGLISH_LATTER_CODE + key) % ENGLISH_ALPHABET_LENGTH));
тоже не очень читается, предлагаю вынести в метод:

private char encryptLetter(char letter) {
......
}

2021-11-06 10:35 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/ShiftAlgorithm.java
> +                stringBuilder.setCharAt(i, (char)((stringBuilder.charAt(i) - FIRST_ENGLISH_LATTER_CODE - key) % ENGLISH_ALPHABET_LENGTH >= 0 ?
аналогично encrypt

2021-11-06 10:35 UTC, lo0ken commented on Encryption-Decryption/src/encryptdecrypt/UnicodeAlgorithm.java
> +
тут методы смотрятся намного лучше

2021-11-06 14:13 UTC, closed without merging